/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.11 scene.gltf 
Author: BlackCube (https://sketchfab.com/blackcube4)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/garbage-can-trashcan-bin-926826667ff04fb09a0907bbec54c766
Title: Garbage can / trashcan / bin
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/scene.gltf')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.12}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group scale={[1, 1.06, 1]}>
            <mesh geometry={nodes.Object_4.geometry} material={materials.Mlleimer_Boden} />
            <mesh geometry={nodes.Object_5.geometry} material={materials.Mlleimer_Gitter_2} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/scene.gltf')
