/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.11 scene.gltf 
Author: NameSsis (https://sketchfab.com/NameSsis)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/modern-clock-2dfba47d8eab42a3aab00bebf1ee9c80
Title: Modern Clock
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/scene.gltf')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="clockfbx" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
            <group name="Object_2">
              <group name="RootNode">
                <group name="Plane002" position={[0.234, 14.998, 0]} rotation={[-2.951, 0, 0]} scale={100}>
                  <mesh name="Plane002_metal_0" geometry={nodes.Plane002_metal_0.geometry} material={materials.metal} />
                </group>
                <group name="Plane003" position={[0.121, 14.998, 0]} rotation={[-0.966, 0, 0]} scale={100}>
                  <mesh name="Plane003_metal_0" geometry={nodes.Plane003_metal_0.geometry} material={materials.metal} />
                </group>
                <group name="Plane" position={[0, 14.998, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                  <mesh name="Plane_Material_0" geometry={nodes.Plane_Material_0.geometry} material={materials.Material} />
                </group>
                <group name="Cylinder" position={[0, 15.122, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                  <mesh name="Cylinder_metal_0" geometry={nodes.Cylinder_metal_0.geometry} material={materials.metal} />
                </group>
                <group name="Plane001" position={[0.892, 14.998, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                  <mesh name="Plane001_Material001_0" geometry={nodes.Plane001_Material001_0.geometry} material={materials['Material.001']} />
                </group>
                <group name="Cylinder001" position={[0.038, 14.998, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                  <mesh name="Cylinder001_metal_0" geometry={nodes.Cylinder001_metal_0.geometry} material={materials.metal} />
                </group>
                <group name="Plane004" position={[0, 15.006, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                  <mesh name="Plane004_metal_0" geometry={nodes.Plane004_metal_0.geometry} material={materials.metal} />
                </group>
                <group name="Plane005" position={[0, 14.994, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                  <mesh name="Plane005_metal_0" geometry={nodes.Plane005_metal_0.geometry} material={materials.metal} />
                </group>
                <group name="Cube" position={[0.038, 14.998, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                  <mesh name="Cube_Material002_0" geometry={nodes.Cube_Material002_0.geometry} material={materials['Material.002']} />
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/scene.gltf')
